baseURL = "https://citysec.nyc/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "citySec"
theme = "beautifulhugo"
enableEmoji = true

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  #homeTitle = "cybersecurity at city" # Set a different text for the header on the home page
  #subtitle = "you a hacker now baby"
  logo = "/img/lock-icon-avatar-bw-422x422.png"
  favicon = "/img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
  gcse = "009810452597696223009:mpr435y0lus" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/circuit-board-top-bar.jpg"
  #desc = "Sphere"
  position = "center top"     # position: see values of CSS background-position.

[Author]
#  name = "Some Person"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
github = "citysec"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  linkedin = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  youtube = "user/username" # or channel/channelname
#  telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Events"
    url = "page/events/"
    weight = 2

[[menu.main]]
    name = "Resources"
    url = "page/resources/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5
