baseURL = "https://citysec.nyc/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "#citySec"
theme = "beautifulhugo"
enableEmoji = true

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "#citySec" # Set a different text for the header on the home page
  subtitle = "you're a hacker now baby"
  logo = "/img/lock-icon-avatar-bw-422x422.png"
  favicon = "/img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  useHLJS = true
  socialShare = false

[[Params.bigimg]]
  src = "img/bkgc1.gif"
  #desc = "Sphere"
  position = "center top"     # position: see values of CSS background-position.

[Author]
  name = "Chantelle"
#  website = "yourwebsite.com"
# email = ""
#  github = "citysec"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "paranoidprog"
#  linkedin = ""

[[menu.main]]
    name = "projects"
    url = "page/projects/"
    weight = 4

[[menu.main]]
    name = "careers"
    url = "page/careers/"
    weight = 5

[[menu.main]]
    name = "events"
    url = "page/events/"
    weight = 2

[[menu.main]]
    name = "resources"
    url = "page/resources/"
    weight = 3

[[menu.main]]
    name = "about"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "mailing list"
    url = "https://protonmail.us20.list-manage.com/subscribe?u=961d81285d786b9d4b77825c2&id=7bbc63dd45"
    weight = 6
