baseURL = "https://citysec.nyc/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "#citySec"
theme = "beautifulhugo"
enableEmoji = true

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  #homeTitle = "cybersecurity at city" # Set a different text for the header on the home page
  #subtitle = "you a hacker now baby"
  logo = "/img/lock-icon-avatar-bw-422x422.png"
  favicon = "/img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = true

[[Params.bigimg]]
  src = "img/sphere.jpg"
  #desc = "Sphere"
  position = "center top"     # position: see values of CSS background-position.

[Author]
#  name = "Some Person"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
github = "citysec"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  linkedin = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  youtube = "user/username" # or channel/channelname
#  telegram = "username"

[[menu.main]]
    name = "blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "events"
    url = "page/events/"
    weight = 2

[[menu.main]]
    name = "resources"
    url = "page/resources/"
    weight = 3

[[menu.main]]
    name = "about"
    url = "page/about/"
    weight = 4
